// Builds src/lib/commonness-data.ts: how common each birthday is in the US (06-seo.md, "Commonness rank").
// Source: FiveThirtyEight's births data (CC BY 4.0), github.com/fivethirtyeight/data/tree/master/births.
// Years 1994–1999 come from the CDC/NCHS file and 2000–2014 from the SSA file (the files overlap in 2000–2003;
// SSA wins there so every year is counted once). Run again only if the source changes: `pnpm data:commonness`.
import { writeFileSync } from "node:fs";
import { allMonthDays, isLeapDay, toKey } from "@/lib/birthday";

const BASE = "https://raw.githubusercontent.com/fivethirtyeight/data/master/births/";
const FILES = [
  { name: "US_births_1994-2003_CDC_NCHS.csv", from: 1994, to: 1999 },
  { name: "US_births_2000-2014_SSA.csv", from: 2000, to: 2014 },
];

const totals = new Map<string, { births: number; years: number }>();
for (const file of FILES) {
  const res = await fetch(BASE + file.name);
  if (!res.ok) throw new Error(`${file.name}: HTTP ${res.status}`);
  const rows = (await res.text()).trim().split("\n").slice(1);
  for (const row of rows) {
    const [year, month, day, , births] = row.split(",").map(Number) as [number, number, number, number, number];
    if (year < file.from || year > file.to) continue;
    const key = toKey({ month, day });
    const t = totals.get(key) ?? { births: 0, years: 0 };
    t.births += births;
    t.years += 1;
    totals.set(key, t);
  }
}

// Average births on each date in the years it happened. Feb 29 is ranked last whatever its average:
// it only happens once every four years, so it's the rarest birthday by far (06-seo.md).
const days = allMonthDays().map((md) => {
  const t = totals.get(toKey(md));
  if (!t) throw new Error(`No births data for ${toKey(md)}`);
  return { key: toKey(md), leap: isLeapDay(md), avg: t.births / t.years };
});
days.sort((a, b) => Number(a.leap) - Number(b.leap) || b.avg - a.avg);

const lines = days.map((d, i) => `  "${d.key}": [${i + 1}, ${Math.round(d.avg)}],`).sort();
const years = FILES.map((f) => `${f.from}–${f.to}`).join(", ");
writeFileSync(
  "src/lib/commonness-data.ts",
  `// Generated by scripts/build-commonness.ts from FiveThirtyEight's US births data (${years}). Do not edit.
// month-day → [rank out of 366 (1 = most common), average US births on that date per year it occurred]
export const COMMONNESS: Record<string, readonly [rank: number, births: number]> = {
${lines.join("\n")}
};
`,
);
console.log(`Wrote ${days.length} dates. Most common: ${days[0]!.key}, least common (not Feb 29): ${days[364]!.key}`);
